/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

#include "sysTick.h"
#include "can.h"
#include "uart.h"
#include "adxl345.h"
#include "vibration.h"
#include "fft.h"
#include "hallEffect_a3144.h"
#include "iwdg.h"

#define DWT_CTRL (*(volatile uint32_t *)(0xE0001000))

uint16_t receivedID;
uint8_t  receivedDLC;
uint16_t receivedTimeStamp;
uint64_t receivedMsg;

uint8_t flag_msgReceived = 0;

arm_status FFT_status;
VibrationFFTResult_t result;


TaskHandle_t AccelerationTaskHandle;
TaskHandle_t ProcessTimeDomainTaskHandle;
TaskHandle_t ProcessFreqDomainTaskHandle;
TaskHandle_t DisplayResultTaskHandle;
TaskHandle_t iwdgTaskHandle;
TaskHandle_t CANTaskHandle;

QueueHandle_t TDtoCANQueueHandle;
QueueHandle_t FDtoCANQueueHandle;

static void Enable_FPU(void){
	SCB->CPACR |= (3UL << 20) | (3UL << 22);

	__DSB();
	__ISB();
}

void AccelarationTask(void* param){

	while(1){
		VibrationSamplingTask();
		vTaskDelay(pdMS_TO_TICKS(0.25));
	}
}

void ProcessTimeDomainTask(void* param){

	while(1){
		ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
		Vibration_ProcessTimeDomain();
	}
}

void ProcessFreqDomainTask(void* param){

	while(1){
		ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
		Vibration_ProcessFreqDomain();
	}
}

void DisplayResultTask(void* param){

	while(1){
		vTaskDelay(pdMS_TO_TICKS(100));

		Vibration_PrintResult();

	}
}

void iwdgTask(void *argument)
{
    while (1)
    {
    	Watchdog_Refresh();
        vTaskDelay(pdMS_TO_TICKS(50));
    }
}

void CAN_Task(void *argument){
	VibrationResult_t receiveTD ;
	FFT_Peak_t receiveFD;

    while (1)
    {

    	if (xQueueReceive(TDtoCANQueueHandle, &receiveTD, portMAX_DELAY) == pdPASS){
    		CAN_SendWord(receiveTD.rms);
    		CAN_SendWord(receiveTD.peak);
    		CAN_SendWord(receiveTD.crest_factor);
    	}
    	for(uint8_t i=0 ; i<3; i++){
    		if (xQueueReceive(FDtoCANQueueHandle, &receiveFD, portMAX_DELAY) == pdPASS){
    			CAN_SendWord(receiveFD.frequency);
				CAN_SendWord(receiveFD.magnitude);
				CAN_SendWord(receiveFD.bin);
			}
    	}
    	CAN_SendWord(A3144_GetRPM());
    	//Send Fault Messages or Any Sort of Message after computing here

    }
}
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName){
    taskDISABLE_INTERRUPTS();

    while (1)
    {
    }
}

int main(void)
{
	//Initialization
	Enable_FPU();

//	SysTick_config();
	CAN1_Init();
	UART2_RxTxInit();
	A3144_Init();
	Vibration_Init();
	FFT_status = FFT_Init();

    DWT_CTRL |= (1<<0);

    SEGGER_SYSVIEW_Conf();
    vSetVarulMaxPRIGROUPValue();
    SEGGER_SYSVIEW_Start();

	TDtoCANQueueHandle = xQueueCreate(10, sizeof(VibrationResult_t));
	FDtoCANQueueHandle = xQueueCreate(10, sizeof(FFT_Peak_t));

	configASSERT(TDtoCANQueueHandle != NULL);
	configASSERT(FDtoCANQueueHandle != NULL);

	BaseType_t TaskCreationStatus;

	TaskCreationStatus = xTaskCreate(AccelarationTask, "ADXL", 1024, NULL, 1, &AccelerationTaskHandle);
	configASSERT(TaskCreationStatus == pdPASS);

	TaskCreationStatus = xTaskCreate(ProcessTimeDomainTask, "TD", 1024, NULL, 2, &ProcessTimeDomainTaskHandle);
	configASSERT(TaskCreationStatus == pdPASS);

	TaskCreationStatus = xTaskCreate(ProcessFreqDomainTask, "FD", 1024, NULL, 2, &ProcessFreqDomainTaskHandle);
	configASSERT(TaskCreationStatus == pdPASS);

	TaskCreationStatus = xTaskCreate(DisplayResultTask, "Display", 1024, NULL, 1, &DisplayResultTaskHandle);
	configASSERT(TaskCreationStatus == pdPASS);

	TaskCreationStatus = xTaskCreate(iwdgTask, "IWDG", 256, NULL, 3, &iwdgTaskHandle);
	configASSERT(TaskCreationStatus == pdPASS);

	TaskCreationStatus = xTaskCreate(CAN_Task, "CAN", 1024, NULL, 2, &CANTaskHandle);
	configASSERT(TaskCreationStatus == pdPASS);

	vTaskStartScheduler();

}
