/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "main.h"
#include <stdint.h>
#include <string.h>

#include "can.h"
#include "sysTick.h"
#include "uart.h"

uint16_t receivedID;
uint8_t  receivedDLC;
uint16_t receivedTimeStamp;
uint64_t receivedMsg;

uint8_t flag_msgReceived = 0;

static void Clock_Init_16MHz(void)
{
    /*
     * HSI = 8 MHz
     * PLL input = HSI / 2 = 4 MHz
     * PLL multiplier = x4
     * SYSCLK = 4 MHz x 4 = 16 MHz
     */

    /* Enable HSI */
    RCC->CR |= RCC_CR_HSION;

    /* Wait for HSI ready */
    while (!(RCC->CR & RCC_CR_HSIRDY)) { }

    // Set AHB prescaler = /1
    RCC->CFGR &= ~RCC_CFGR_HPRE;

    //Set APB1 prescaler = /1
    RCC->CFGR &= ~RCC_CFGR_PPRE1;

    //Set APB2 prescaler = /1
    RCC->CFGR &= ~RCC_CFGR_PPRE2;

    //PLL source = HSI/2 --> PLLSRC = 0
    RCC->CFGR &= ~RCC_CFGR_PLLSRC;

    //PLL multiplication factor = x4 --> PLLMUL[3:0] = 0010
    RCC->CFGR &= ~RCC_CFGR_PLLMULL;
    RCC->CFGR |= RCC_CFGR_PLLMULL4;

    //Enable PLL
    RCC->CR |= RCC_CR_PLLON;

    /* Wait for PLL ready */
    while (!(RCC->CR & RCC_CR_PLLRDY)){ }

    //Select PLL as SYSCLK --> SW = 10
    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_PLL;

    //Wait until PLL becomes SYSCLK
    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL) { }
}

static void LED_Init(void){
	/* 1. Enable GPIOC clock */
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;

	/* 2. Configure PC13 as General Purpose Output Push-Pull, 2 MHz */
	GPIOC->CRH &= ~(GPIO_CRH_MODE13 | GPIO_CRH_CNF13);

	GPIOC->CRH |= GPIO_CRH_MODE13_1;
	GPIOC->CRH &= ~GPIO_CRH_CNF13;

	/* LED OFF initially */
	GPIOC->BSRR = GPIO_BSRR_BS13;
}

int main(void)
{

//	Clock_Init_16MHz();

	UART2_RxTxInit();
	//CAN1_LoopBack();
	printf("\r\nUART Initialised");

	printf("\r\nSTM32 Started......");
	//Initialization
	SysTick_config();
	printf("\r\nSysTick Initialised");
	LED_Init();
	printf("\r\nLED Initialised");
	CAN1_Init();
	printf("\r\nCAN Initialised");
//	CAN1_LoopBack();
//	printf("\r\nCAN Loopback");

	uint32_t now = 0;

	char *MSG = "ShellMsg";
	uint8_t len = strlen(MSG);
	uint8_t buf[9] = {0};

	while(1){

		if((sysTick - now) >= 1000){
//			CAN1_TxMsg((uint8_t *)MSG, len);
			GPIOC->ODR ^= GPIO_ODR_ODR13;
			printf("\r\nFunctioning....");
			now = sysTick;
		}

		if(flag_msgReceived){

			memcpy(buf, &receivedMsg, receivedDLC);
			buf[receivedDLC] = '\0';
			printf("\r\nReceived : %s @ %ld\r\n",buf,sysTick);
			flag_msgReceived = 0;
		}
	}
}
