/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "sysTick.h"
#include "uart_LIN.h"

uint8_t flag_msgReceived;
uint8_t RxBuf[11] = {};

int main(void)
{
	//Initialization
	SysTick_config();
	LIN_Init();

	uint32_t now = 0;

	uint8_t MSG[8] = "ROCKHARD";
	uint8_t len = sizeof(MSG);

	LIN_Transmit(0x01, MSG, len);

	while(1){
//		if((sysTick - now) >= 1000){
//
//			LIN_Transmit(0x01,MSG, len);
//			now = sysTick;
//		}

//		if(flag_msgReceived){
//
//			for(int i=0;i<11;i++){
//				RxBuf[i]=LIN_Receive();
//
//				printf("RCVD [%d]: %d", i, RxBuf[i]);
//			}
//
//			flag_msgReceived = 0;
//
//		}
	}
}
