/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "sysTick.h"
#include "uart_LIN.h"
#include "can.h"
#include "comm_stats.h"



extern uint16_t receivedID;
extern uint8_t  receivedDLC;
extern uint16_t receivedTimeStamp;
extern uint64_t receivedMsg;
extern uint8_t CAN_msgReceived;

extern CommStats_t LIN_Stats;
extern CommStats_t CAN_Stats;

extern uint8_t LIN_msgReceived;
uint8_t RxBuf[11] = {};

int main(void)
{
	//Initialization
	SysTick_config();
	CommStats_Init();

	LIN_Init();

	CAN1_Init();
	//CAN1_LoopBack();

	printf("Starting ECU1.... \n\r");
	uint32_t now = 0;

	char *CAN_MSG = "OpenECU1";
	uint8_t size = strlen(CAN_MSG);
	uint8_t buf[9] = {0};

	uint8_t LIN_MSG[8] = "HI_LIN1";
	uint8_t len = sizeof(LIN_MSG);

//	LIN_Transmit(0x01, LIN_MSG, len);

	while(1){
		//CAN Transmission
		if((sysTick - now) >= 1){
			CAN1_TxMsg((uint8_t *)CAN_MSG, size);
			now = sysTick;
		}

		if(CAN_msgReceived){
			memcpy(buf, &receivedMsg, receivedDLC);
			buf[receivedDLC] = '\0';
			printf("Received : %s @ %ld\n\r",buf,sysTick);
			CAN_msgReceived = 0;
		}
		//LIN Transmission
//		if((sysTick - now) >= 250){
//
//			LIN_Transmit(0x01,LIN_MSG, len);
//			now = sysTick;
//		}

//		if(LIN_msgReceived){
//
//			for(int i=0;i<11;i++){
//				RxBuf[i]=LIN_Receive();
//
//				printf("RCVD [%d]: %d", i, RxBuf[i]);
//			}
//			LIN_msgReceived = 0;
//		}

		// Stats
//		if(LIN_Stats.TxPackets%100 == 0)
//		{
//		    CommStats_Print(&LIN_Stats,"LIN");
//		}

		if((CAN_Stats.TxPackets%1000 == 0)&& (CAN_Stats.TxPackets != 0))
		{
		    CommStats_Print(&CAN_Stats,"CAN");
		}

	}
}


