/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "sysTick.h"
#include "can.h"

#include "adxl345.h"
#include "vibration.h"
#include "fft.h"
#include "hallEffect_a3144.h"

uint16_t receivedID;
uint8_t  receivedDLC;
uint16_t receivedTimeStamp;
uint64_t receivedMsg;

uint8_t flag_msgReceived = 0;

arm_status FFT_status;

static void Enable_FPU(void){
	SCB->CPACR |= (3UL << 20) | (3UL << 22);

	__DSB();
	__ISB();
}

int main(void)
{
	//Initialization
	Enable_FPU();

	SysTick_config();
	CAN1_Init();

//	ADXL345_Init();
	A3144_Init();
	Vibration_Init();
	FFT_status = FFT_Init();
	//CAN1_LoopBack();

	VibrationSamplingTask();

	FFT_Process(const VibrationSample_t *input,  VibrationFFTResult_t *result)
//    uint8_t now = 0;
//    ADXL345_RawData_t data;
//    uint32_t period = 0;

//	while(1){
//		if(sysTick - now > 1000){
////			ADXL345_ReadXYZ(&data);
////			period = A3144_GetCapturePeriod();
////			printf("Raw Data:\n x: %d  y: %d  z: %d\n\r",data.x, data.y, data.z);
////			printf("Period : %lu\n\r", period);
//
//			now = sysTick;
//		}
//	}
}
