/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "sysTick.h"
#include "can.h"
#include "ds18b20.h"
#include "timer.h"
#include "fan.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

typedef struct
{
    int16_t temperature_x100;

} TemperatureData_t;

static QueueHandle_t temperatureQueue;

static TaskHandle_t temperatureTaskHandle;
static TaskHandle_t coolerTaskHandle;

static void TemperatureTask(void *argument)
{
    TemperatureData_t temperatureData;
    (void)argument;

    while (1)
    {
        temperatureData.temperature_x100 = DS18B20_ReadTemperature();

        xQueueOverwrite( temperatureQueue, &temperatureData);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

static void CoolerTask(void *argument)
{
    TemperatureData_t temperatureData;
    int16_t temperature;
    uint8_t fanSpeed;

    (void)argument;

    while (1)
    {
    	//Wait for latest temperature
        if (xQueueReceive(temperatureQueue, &temperatureData, portMAX_DELAY) == pdPASS)
        {
            temperature = temperatureData.temperature_x100;

            if (temperature == INT16_MIN)
            {
                Fan_Stop();
                fanSpeed = 0U;
                printf("DS18B20 ERROR\r\n");
                continue;
            }

            printf("T : %d.%02d C\r\n", temperature / 100, temperature % 100);

            if (temperature < 2000)
            {
                fanSpeed = 0U;
            }
            else if (temperature < 3000)
            {
                fanSpeed = 30U;
            }
            else if (temperature < 3500)
            {
                fanSpeed = 50U;
            }
            else if (temperature < 4000)
            {
                fanSpeed = 70U;
            }
            else if (temperature < 4500)
            {
                fanSpeed = 85U;
            }
            else
            {
                fanSpeed = 100U;
            }
            Fan_SetSpeed(fanSpeed);

            printf("Fan : %d %%\r\n", fanSpeed);
        }
    }
}

//uint16_t receivedID;
//uint8_t  receivedDLC;
//uint16_t receivedTimeStamp;
//uint64_t receivedMsg;
//
//uint8_t flag_msgReceived = 0;

//static int16_t temperature_x100 = 0;
//static uint8_t fanSpeed = 0;
//
//void Cooler_control(void){
//	int16_t temperature;
//	temperature = DS18B20_ReadTemperature();
//
//	if (temperature == INT16_MIN)
//	{
//		Fan_Stop();
//		fanSpeed = 0U;
//		return;
//	}
//
//	temperature_x100 = temperature;
//
//	if (temperature < 2000)
//	{
//		fanSpeed = 0U;
//	}
//	else if (temperature < 3000)
//	{
//		fanSpeed = 30U;
//	}
//	else if (temperature < 3500)
//	{
//		fanSpeed = 50U;
//	}
//	else if (temperature < 4000)
//	{
//		fanSpeed = 70U;
//	}
//	else if (temperature < 4500)
//	{
//		fanSpeed = 85U;
//	}
//	else
//	{
//		fanSpeed = 100U;
//	}
//
//	Fan_SetSpeed(fanSpeed);
//}

int main(void)
{
	//Initialization
	//SysTick_config();
	CAN1_Init();

	Timer_Init();  //TIM2
    DS18B20_Init();
    Fan_Init();

	//CAN1_LoopBack();
    temperatureQueue = xQueueCreate(1, sizeof(TemperatureData_t));
    if (temperatureQueue == NULL){
		while (1){}
    }
    xTaskCreate(
	   TemperatureTask,
	   "Temperature",
	   256,
	   NULL,
	   2,
	   &temperatureTaskHandle
   );

   xTaskCreate(
	   CoolerTask,
	   "Cooler",
	   256,
	   NULL,
	   2,
	   &coolerTaskHandle
   );

   vTaskStartScheduler();


//  uint32_t now = 0;

//	char *MSG = "OpenECU1";
//	uint8_t len = strlen(MSG);
//	uint8_t buf[9] = {0};

	while(1){

//		if((sysTick - now) >= 1000){
//			printf("T : %d\r\n",DS18B20_ReadTemperature());
//			Cooler_control();
//			//Fan_SetSpeed(80);
//			now = sysTick;
//		}
//		if((sysTick - now) >= 1000){
//
//			CAN1_TxMsg((uint8_t *)MSG, len);
//			now = sysTick;
//		}
//
//		if(flag_msgReceived){
//			memcpy(buf, &receivedMsg, receivedDLC);
//			buf[receivedDLC] = '\0';
//			printf("Received : %s @ %ld\n\r",buf,sysTick);
//			flag_msgReceived = 0;
//		}
	}
}
